# Codecov configuration for smart-http-proxy
coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 1%
        
  ignore:
    - "tests/**/*"
    - "dist/**/*"
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - "jest.config.js"
    - "eslint.config.js"

comment:
  layout: "header,diff,flags,files,footer"
  behavior: default
  require_changes: false