version: '3.8'

services:
  proxy-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smart-proxy-dev
    ports:
      - "7777:7777"
    environment:
      - TARGET_URLS=httpbin:80|nginx:80
      - TIMEOUT=5000
      - PORT=7777
      - HOST=0.0.0.0
      - LOG_LEVEL=debug
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./logs:/app/logs
      # Exclude node_modules from mount
      - /app/node_modules
    networks:
      - proxy-network
    depends_on:
      - httpbin
      - nginx

  httpbin:
    image: kennethreitz/httpbin:latest
    container_name: httpbin-dev
    ports:
      - "8080:80"
    networks:
      - proxy-network

  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge