name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build, Test & Quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Tests
      run: yarn test --passWithNoTests

    - name: Lint
      run: yarn lint

    - name: Security audit
      run: yarn security:audit || true  # Don't fail on warnings

    - name: Smoke test
      run: |
        # Simple integration test
        node -e "
        const http = require('http');
        http.createServer((req, res) => {
          res.writeHead(200, {'Content-Type': 'application/json'});
          res.end(JSON.stringify({status: 'ok'}));
        }).listen(3001);
        " &
        
        sleep 2
        
        TARGET_URLS="localhost:3001" PORT=7777 LOG_LEVEL="error" timeout 10s node dist/index.js &
        sleep 3
        
        curl -f http://localhost:7777/health
        curl -f http://localhost:7777/metrics  
        curl -f http://localhost:7777/prometheus
        
        echo "✅ All endpoints working"